#!/bin/bash
set -uo pipefail
IFS=$'\n\t'

R='\033[0;31m'; G='\033[0;32m'; Y='\033[1;33m'; B='\033[0;34m'; C='\033[0;36m'; NC='\033[0m'; BOLD='\033[1m'; NL='\r\033[K'

error() { echo -e "${R}[ERR]${NC}  $1"; exit 1; }

cwd() {
    source=${BASH_SOURCE[0]}
    while [ -L "$source" ]; do
        target="$(readlink "$source")"
        if [[ $target == /* ]]; then
            source="$target"
        else
            dir="$(dirname "$source")"
            source="$dir/$target"
        fi
    done
    dirname "$source"
}

banner() {
    echo -e "${C}=================================${NC}"
    echo -e "${C}   POCKER - Non Root Container   ${NC}"
    echo -e "${C}=================================${NC}"
}

help() {
    banner
    echo -e ""
    echo -e "Usage: $(basename $0) <command> <args...>"
    echo -e "Commands:"
    echo -e "  - ${BOLD}ls${NC}                                  List of created containers"
    echo -e "    - ${BOLD}ls${NC} container                      List of created containers"
    echo -e "    - ${BOLD}ls${NC} image                          List of downloaded images"
    echo -e "  - ${BOLD}search${NC} <keyword>                    Search available images"
    echo -e "  - ${BOLD}pull${NC} <image>[:tag]                  Download image(s)"
    echo -e "  - ${BOLD}create${NC} <image> <container_name>     Create container"
    echo -e "  - ${BOLD}login${NC} <container_name>              Enter container shell"
    echo -e "  - ${BOLD}rm${NC} <container_name>                 Remove container(s)"
    echo -e "    - ${BOLD}rm${NC} container <container_name>     Remove container(s)"
    echo -e "    - ${BOLD}rm${NC} image <image>                  Remove image(s)"
    exit 0
}

resolve_image_name() {
    RAW_IMAGE="$1"
    if [[ "$RAW_IMAGE" =~ ^([^/]+\.[^/]+)/(.+)$ ]]; then
        REPO_TAG="${BASH_REMATCH[2]}"
    else
        REPO_TAG="$RAW_IMAGE"
        [[ "$REPO_TAG" != *"/"* ]] && REPO_TAG="library/$REPO_TAG"
    fi

    if [[ "$REPO_TAG" == *":"* ]]; then
        REPO=${REPO_TAG%%:*}
        TAG=${REPO_TAG##*:}
    else
        REPO=$REPO_TAG
        TAG="latest"
    fi

    echo "$REPO:$TAG"
}

alphanum() {
    echo "$1" | sed -e 's/[^a-zA-Z0-9]/_/g'
}

regsave() {
    printf '%s\n' "$1" | sed -e 's/[][(){}.^$*+?|\\/]/\\&/g'
}

layer_extract() {
    in="$1"
    out="$2"
    layers="$3"

    for layer in $layers; do
        [ ! -f "$in/$layer" ] && \
            echo -e "${R}[ERR]${NC} Missing digest: $layer" && \
            return 1

        echo -ne "${Y}[WAIT]${NC} Extract $layer..."
        if proot --link2symlink \
            tar --no-same-owner \
                --no-same-permissions \
                -xpf "$in/$layer" \
                -C "$out"; then
            echo -e "${NL}Extract $layer ${G}[OK]${NC}"
        else
            echo -e "${NL}Extract $layer ${R}[FAIL]${NC}"
            return 1
        fi
    done
    echo "nameserver 1.1.1.1" >> "$ROOTFS_DIR/$container_path/etc/resolv.conf"
    chown -R $(whoami):$(whoami) "$ROOTFS_DIR/$container_path"
    chmod u+w -R "$ROOTFS_DIR/$container_path"
    return 0
}

HAS_REQUIREMENT=0
for cmd in git curl jq proot tar xz; do
    if ! type $cmd > /dev/null 2>&1; then
        echo -e "${R}[ERR]${NC} Missing deps: $cmd"
        HAS_REQUIREMENT=1
    fi
done
[ $HAS_REQUIREMENT -ne 0 ] && exit 1

if [ $# -lt 1 ] || [ "$1" = "help" ]; then
    help
fi

CACHE_DIR="$(cwd)/.cache"
ROOTFS_DIR="$(cwd)/.rootfs"
CACHE_STATE="$CACHE_DIR/state"
ROOTFS_STATE="$ROOTFS_DIR/state"

[ ! -e "$CACHE_DIR" ] && mkdir -p "$CACHE_DIR"
[ ! -e "$ROOTFS_DIR" ] && mkdir -p "$ROOTFS_DIR"
[ ! -f "$ROOTFS_STATE" ] && touch "$ROOTFS_STATE"
[ ! -f "$CACHE_STATE" ] && touch "$CACHE_STATE"

pull() {
    image="$1"
    full_image="$(resolve_image_name "$image")"
    path="$(alphanum "$full_image")"

    if grep -q "^$full_image " "$CACHE_STATE"; then
        error "$image already installed."
    fi

    mkdir -p "$CACHE_DIR/$path"
    $(cwd)/image_pull "$CACHE_DIR/$path" "$full_image"
    if [ $? -eq 0 ]; then
        printf "$full_image $path\n" >> "$CACHE_STATE"
    else
        rm -rf "$CACHE_DIR/$path"
    fi
}

delete_image() {
    image="$1"
    full_image="$(resolve_image_name "$image")"
    path="$(alphanum "$full_image")"
    regex="^$(regsave "$full_image") "
    target="$CACHE_DIR/$path"

    if [ ! -e "$target" ] && ! grep -q "^$full_image " "$CACHE_STATE"; then
        error "Image \"$image\" is not installed."
    fi

    rm -rf "$target"
    sed -i "/$regex/d" "$CACHE_STATE"
    echo -e "${G}[OK]${NC}  Image \"$image\" deleted."
}

delete_container() {
    container="$1"
    path="$(alphanum "$container")"
    target="$ROOTFS_DIR/$path"

    if [ ! -e "$target" ] && ! awk -F'\t' -v c="$container" '$2==c{found=1; exit} END{exit !found}' "$ROOTFS_STATE" > /dev/null 2>&1; then
        error "Container \"$container\" is not found."
    fi

    rm -rf "$target"
    sed -i "/\t$(regsave "$container")\t/d" "$ROOTFS_STATE"
    echo -e "${G}[OK]${NC}  Container \"$container\" deleted."
}

command="$1"
case $command in
    search)
        image="$2"
        results=$(curl -fsSL "https://hub.docker.com/search?q=$image" | grep -oP 'data-discover="true">\K[^<]+')
        if [[ -z "$results" ]]; then
            echo "Result is empty."
        else
            for img in $results; do
                echo -e " ${G}-${NC} $img"
            done
        fi
        ;;
    pull)
        shift 1
        target=($@)
        for img in "${target[@]}"; do
            pull $img
        done
        ;;
    create)
        image="$2"
        container="$3"
        container_path="$(alphanum "$container")"
        full_image="$(resolve_image_name "$image")"
        image_path="$(alphanum "$full_image")"

        if [ ! -e "$CACHE_DIR/$image_path" ] && ! grep -q "^$full_image" "$CACHE_STATE"; then
            error "$image is not installed."
        fi

        if [ -e "$ROOTFS_DIR/$container_path" ] || awk -F'\t' -v c="$container" '$2==c{found=1; exit} END{exit !found}' "$ROOTFS_STATE" > /dev/null 2>&1; then
            error "Container named '$container' already exists."
        fi

        [[ ! -e "$CACHE_DIR/$image_path" || ! -e "$CACHE_DIR/$image_path/manifest.json" ]] && \
            error "Couldn't create container from '$image' because it might be corrupted."

        mkdir -p "$ROOTFS_DIR/$container_path"
        layer_extract "$CACHE_DIR/$image_path" "$ROOTFS_DIR/$container_path" "$(cat "$CACHE_DIR/$image_path/manifest.json" | jq -r .Layers[])"

        if [ $? -eq 0 ]; then
            echo -e "${G}[OK]${NC} Container '$container' successfully created."
            echo -e "Use '${BOLD}$(basename $0) login $container${NC}' to enter container"
        else
            error "Failed create container"
        fi
        printf "$full_image\t$container\t$container_path\n" >> "$ROOTFS_STATE"
        ;;
    ls)
        mode="container"
        if [ $# -gt 1 ]; then
            case "$2" in
                image)
                    mode="image"
                    ;;
                container)
                    mode="container"
                    ;;
                *)
                    mode=""
                    ;;
            esac
        fi


        case "$mode" in
            image)
                result=$(cat "$CACHE_STATE" | awk '{print $1}')
                if [ -z "$result" ]; then
                    echo "No image downloaded."
                else
                    for r in $result; do
                        echo -e " ${G}-${NC} $r"
                    done
                fi
                ;;
            container)
                result=$(awk '{ printf "%-8s | %s\n", $2, $1 }' "$ROOTFS_STATE")
                if [ -z "$result" ]; then
                    echo "No container created."
                else
                    for r in $result; do
                        echo -e "$r"
                    done
                fi
                ;;
            *) help;;
        esac
        ;;
    login)
        container="$2"
        container_path="$(alphanum "$container")"
        target="$ROOTFS_DIR/$container_path"
        use_proot=1

        if [ ! -e "$target" ] || awk -F'\t' -v c="$container" '$2==c{found=1; exit} END{exit found}' "$ROOTFS_STATE" > /dev/null 2>&1; then
            error "Container named '$container' is not exists."
        fi

        shell="/bin/sh"
        if [ -f "$target/bin/bash" ]; then
            shell="/bin/bash"
        elif [ -f "$target/bin/ash" ]; then
            shell="/bin/ash"
        fi

	if [[ $use_proot -eq 1 ]]; then
		env -i \
		    HOSTNAME="$container" \
		    LANG=C.UTF-8 \
		    PS1="\$(whoami)@\$HOSTNAME \w \$" \
		    HOME=/root \
		    TERM=xterm-256color \
		    PATH=/usr/bin:/bin:/usr/sbin:/sbin \
		    PROOT_NO_SECCOMP=1 \
		proot -0 \
		    --link2symlink \
		    --kill-on-exit \
		    -r "$target" \
		    -b /dev \
		    -b /proc \
		    -b /sys \
		    -w /root \
		    $shell -lc 'exec '"$shell"' --login -c "export PS1=\"\\u@\\h \\w \\$ \"; exec '"$shell"'"'
	else
		mount --bind /dev  "$target/dev"
		mount -t proc proc "$target/proc"
		mount --bind /sys  "$target/sys"

		env -i \
		    HOSTNAME="$container" \
		    PS1='\u@$HOSTNAME \w \$ ' \
		    HOME=/root \
		    TERM=xterm-256color \
		    PATH=/usr/bin:/bin:/usr/sbin:/sbin \
		    chroot "$target" \
			$shell --login

		umount "$target/dev"
		umount "$target/proc"
		umount "$target/sys"
	fi
        ;;
    rm)
        shift 1
        mode="container"
        target=($@)
        if [ "$1" = "container" ]; then
            shift 1
            target=($@)
        fi
        if [ "$1" = "image" ]; then
            shift 1
            mode="image"
            target=($@)
        fi

        if [[ "$mode" == "container" ]]; then
            for name in "${target[@]}"; do
                delete_container $name
            done
        else
            for name in "${target[@]}"; do
                delete_image $name
            done
        fi
        ;;
    *)
        help
        ;;
esac
